/*
 * (c) Copyright 2018 Palantir Technologies Inc. All rights reserved.
 */

package com.palantir.conjure.java.undertow.demo;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/** Sample API as generated by conjure-undertow. */
public interface MyService {

    /**
     * Increments the given base date by the number of hours.
     */
    OffsetDateTime incrementTime(OffsetDateTime base, int numHours);

    /**
     * Returns a map indicating for each of the given dates whether they are a Sunday or not.
     */
    Map<OffsetDateTime, Boolean> isSunday(List<OffsetDateTime> dates);

    /** Returns the trace ID made available to the server implementation. */
    String returnTrace();

    /** Returns a string iff {@code shouldReturnString == true}. */
    Optional<String> maybeString(boolean shouldReturnString);
}
