ch.qos.logback:* = 1.2.11
com.atlassian.commonmark:* = 0.12.1
com.fasterxml.jackson.*:* = 2.19.2
com.google.auto:auto-common = 1.2.2
com.google.code.findbugs:jsr305 = 3.0.2
com.google.guava:guava = 33.4.8-jre
com.google.testing.compile:compile-testing = 0.21.0
com.palantir.common:streams = 2.4.0
com.palantir.conjure.java.api:* = 2.62.0
com.palantir.conjure.java.runtime:* = 8.23.0
com.palantir.conjure.verification:* = 0.19.0
com.palantir.conjure:* = 4.50.0
com.palantir.deadlines:* = 0.15.0
com.palantir.dialogue:* = 6.7.0
com.palantir.goethe:* = 0.16.0
com.palantir.human-readable-types:* = 1.7.0
com.palantir.javapoet:javapoet = 0.7.0
com.palantir.ri:resource-identifier = 2.11.0
com.palantir.safe-logging:* = 3.9.0
com.palantir.syntactic-paths:syntactic-paths = 0.9.0
com.palantir.tokens:* = 3.18.0
com.palantir.tracing:* = 6.27.0
info.picocli:picocli = 4.7.7
io.undertow:* = 2.2.37.Final
joda-time:joda-time = 2.14.0
org.apache.commons:commons-lang3 = 3.18.0
org.assertj:* = 3.27.4
org.derive4j:* = 1.1.1
org.eclipse.collections:* = 13.0.0
org.glassfish.jersey.*:* = 2.34
org.hamcrest:hamcrest-core = 3.0
org.immutables:value = 2.11.3
org.javassist:javassist = 3.22.0-GA
org.jetbrains:annotations = 26.0.2
org.junit.jupiter:* = 5.13.4
org.junit.platform:* = 1.13.4
org.mockito:* = 5.19.0
org.slf4j:* = 2.0.17
org.wildfly.common:wildfly-common = 2.0.1
jakarta.ws.rs:jakarta.ws.rs-api = 4.0.0
jakarta.validation:jakarta.validation-api = 3.0.0

# dependency-upgrader:OFF
# Generator should be compatible with java 8
com.palantir.javaformat:palantir-java-format = 1.1.0
# Do not force up the minimum error_prone_annotations dependency version
com.google.errorprone:error_prone_annotations = 2.7.1
# Dropwizard is used for testing, do not take major version upgrades
io.dropwizard:dropwizard-* = 4.0.13
# dependency-upgrader:ON
