/*
 * (c) Copyright 2025 Palantir Technologies Inc. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.palantir.conjure.java.parameterized;

import com.google.common.collect.ImmutableList;
import com.palantir.conjure.java.Options;
import com.palantir.conjure.java.parameterized.objects.GeneratorType;
import com.palantir.conjure.java.parameterized.objects.ParameterizedTestCase;
import java.nio.file.Path;
import java.util.List;

public final class TestCases {
    private static final List<ParameterizedTestCase> CASES = ImmutableList.<ParameterizedTestCase>builder()
            .add(ParameterizedTestCase.builder()
                    .name("template")
                    .docs("Testing compilation of example objects with the base set of options from our templates.")
                    .files(Path.of("example-types.yml"))
                    .options(Options.builder()
                            .useImmutableBytes(true)
                            .strictObjects(true)
                            .nonNullCollections(true)
                            .useStagedBuilders(true)
                            .excludeEmptyOptionals(true)
                            .preferObjectBuilders(true)
                            .build())
                    .generatorTypes(GeneratorType.OBJECT)
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("no-static-factory")
                    .docs("Test generating objects without the static factory methods.")
                    .files(Path.of("example-types-no-static-factory.yml"))
                    .options(Options.builder().preferObjectBuilders(true).build())
                    .generatorTypes(GeneratorType.OBJECT)
                    .build())
            // TODO(kkak): This feels slightly redundant to the template case, maybe we could pull out only union types
            .add(ParameterizedTestCase.builder()
                    .name("all-examples")
                    .docs("Test generation of all example objects")
                    .files(Path.of("example-types.yml"))
                    .options(Options.builder()
                            .useImmutableBytes(true)
                            .strictObjects(true)
                            .nonNullCollections(true)
                            .excludeEmptyOptionals(true)
                            .unionsWithUnknownValues(true)
                            .jetbrainsContractAnnotations(true)
                            .build())
                    .generatorTypes(GeneratorType.OBJECT)
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("byte-buffer")
                    .docs("Test compatibility with legacy objects with binary fields.")
                    .files(Path.of("example-binary-types.yml"))
                    .options(Options.builder()
                            .excludeEmptyOptionals(true)
                            .jetbrainsContractAnnotations(true)
                            .build())
                    .generatorTypes(GeneratorType.OBJECT)
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("staged-builder")
                    .docs("Test generation of objects with staged builders.")
                    .files(Path.of("example-staged-types.yml"))
                    .options(Options.builder()
                            .useStagedBuilders(true)
                            .excludeEmptyOptionals(true)
                            .jetbrainsContractAnnotations(true)
                            .build())
                    .generatorTypes(GeneratorType.OBJECT)
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("strict-staged-builder")
                    .docs("Test generation of objects with strict staged builders.")
                    .files(Path.of("example-strict-staged-types.yml"))
                    .options(Options.builder()
                            .useStrictStagedBuilders(true)
                            .excludeEmptyOptionals(true)
                            .jetbrainsContractAnnotations(true)
                            .build())
                    .generatorTypes(GeneratorType.OBJECT)
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("both-strict-staged-builder")
                    .docs("Validate that enabling both staged and strict staged builders is equivalent to only"
                            + " enabling strict staged builders.")
                    .files(Path.of("example-strict-staged-types.yml"))
                    .options(Options.builder()
                            .useStagedBuilders(true)
                            .useStrictStagedBuilders(true)
                            .excludeEmptyOptionals(true)
                            .jetbrainsContractAnnotations(true)
                            .build())
                    .generatorTypes(GeneratorType.OBJECT)
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("exclude-empty-collections")
                    .docs("Testing support for exclusion of empty collections.")
                    .files(Path.of("exclude-empty-collections.yml"))
                    .options(Options.builder()
                            .excludeEmptyCollections(true)
                            .jetbrainsContractAnnotations(true)
                            .build())
                    .generatorTypes(GeneratorType.OBJECT)
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("primitive-collections")
                    .docs("Testing generation of objects with primitive collections.")
                    .files(Path.of("primitive-collections.yml"))
                    .options(Options.builder()
                            .excludeEmptyCollections(true)
                            .nonNullCollections(true)
                            .useStagedBuilders(true)
                            .build())
                    .generatorTypes(GeneratorType.OBJECT)
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("strict-primitive-collections")
                    .docs("Testing generation of objects with primitive collections and strict staged builders.")
                    .files(Path.of("primitive-collections-strict.yml"))
                    .options(Options.builder()
                            .excludeEmptyCollections(true)
                            .nonNullCollections(true)
                            .useStrictStagedBuilders(true)
                            .build())
                    .generatorTypes(GeneratorType.OBJECT)
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("strict-false")
                    .docs("Validating extra properties on empty objects are allowed when the strict objects feature"
                            + " flag is disabled.")
                    .files(Path.of("example-types-strict-objects.yml"))
                    .options(Options.builder()
                            .useImmutableBytes(true)
                            .strictObjects(false)
                            .jetbrainsContractAnnotations(true)
                            .build())
                    .generatorTypes(GeneratorType.OBJECT)
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("errors")
                    .docs("Testing error generation.")
                    .files(Path.of("example-errors.yml"))
                    .files(Path.of("example-errors-other.yml"))
                    .options(Options.builder()
                            .useImmutableBytes(true)
                            .excludeEmptyOptionals(true)
                            .jetbrainsContractAnnotations(true)
                            .build())
                    .generatorTypes(GeneratorType.ERROR)
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("service-vanilla")
                    .docs("Generate dialogue service objects with no additional options.")
                    .files(Path.of("example-service.yml"))
                    .files(Path.of("cookie-service.yml"))
                    .options(Options.empty())
                    .generatorTypes(List.of(GeneratorType.DIALOGUE, GeneratorType.UNDERTOW, GeneratorType.OBJECT))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("dialogue")
                    .docs("Generate dialogue service objects for ete testing.")
                    .files(Path.of("cookie-service.yml"))
                    .files(Path.of("ete-service.yml"))
                    .files(Path.of("ete-binary.yml"))
                    .options(Options.builder().apiVersion("1.2.3").build())
                    .generatorTypes(List.of(GeneratorType.DIALOGUE, GeneratorType.OBJECT))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("exclude-async-interfaces")
                    .docs("Generate dialogue service objects with the exclude async interfaces flag enabled.")
                    .files(Path.of("example-service.yml"))
                    .options(Options.builder()
                            .excludeDialogueAsyncInterfaces(true)
                            .build())
                    .generatorTypes(List.of(GeneratorType.DIALOGUE, GeneratorType.OBJECT))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("undertow-binary")
                    .docs("Generate undertow service objects with binary fields.")
                    .files(Path.of("example-binary.yml"))
                    .options(Options.empty())
                    .generatorTypes(List.of(GeneratorType.UNDERTOW, GeneratorType.OBJECT))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("undertow-name-collisions")
                    .docs("Generate undertow service objects for definition with name collisions.")
                    .files(Path.of("dangerous-name-service.yml"))
                    .options(Options.builder().undertowServicePrefix(true).build())
                    .generatorTypes(List.of(GeneratorType.UNDERTOW, GeneratorType.OBJECT))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("undertow-name-collisions")
                    .docs("Generate undertow service objects for definition with name collisions.")
                    .files(Path.of("dangerous-name-service.yml"))
                    .options(Options.builder().undertowServicePrefix(true).build())
                    .generatorTypes(List.of(GeneratorType.UNDERTOW, GeneratorType.OBJECT))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("undertow-async")
                    .docs("Generate undertow service objects with experimental async flag enabled.")
                    .files(Path.of("undertow-async-endpoint.yml"))
                    .options(Options.builder()
                            .experimentalUndertowAsyncMarkers(true)
                            .build())
                    .generatorTypes(List.of(GeneratorType.UNDERTOW))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("undertow-async-disabled")
                    .docs("Generate undertow service objects with experimental async flag disabled.")
                    .files(Path.of("undertow-async-endpoint.yml"))
                    .options(Options.empty())
                    .generatorTypes(List.of(GeneratorType.UNDERTOW))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("jersey")
                    .docs("Generate jersey service objects.")
                    .files(Path.of("example-service.yml"))
                    .files(Path.of("cookie-service.yml"))
                    .files(Path.of("ete-service.yml"))
                    .files(Path.of("ete-binary.yml"))
                    .options(Options.builder()
                            .requireNotNullAuthAndBodyParams(true)
                            .build())
                    .generatorTypes(List.of(GeneratorType.JERSEY, GeneratorType.OBJECT))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("jersey-binary")
                    .docs("Generate jersey service objects with binary fields.")
                    .files(Path.of("example-binary.yml"))
                    .options(Options.empty())
                    .generatorTypes(List.of(GeneratorType.JERSEY, GeneratorType.OBJECT))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("jersey-binary-response")
                    .docs("Generate jersey service objects with binary fields, with jersey binary responses enabled.")
                    .files(Path.of("example-binary.yml"))
                    .options(Options.builder().jerseyBinaryAsResponse(true).build())
                    .generatorTypes(List.of(GeneratorType.JERSEY, GeneratorType.OBJECT))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("jakarta-service")
                    .docs("Generate jersey service objects with jakarta packages.")
                    .files(Path.of("example-service.yml"))
                    .options(Options.builder().jakartaPackages(true).build())
                    .generatorTypes(List.of(GeneratorType.JERSEY, GeneratorType.OBJECT))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("undertow")
                    .docs("Generate undertow service objects for ete tests.")
                    .files(Path.of("ete-service.yml"))
                    .files(Path.of("ete-binary.yml"))
                    .files(Path.of("alias-test-service.yml"))
                    .files(Path.of("external-long-test-service.yml"))
                    .files(Path.of("example-endpoint-errors.yml"))
                    .options(Options.builder()
                            .undertowServicePrefix(true)
                            .nonNullCollections(true)
                            .excludeEmptyOptionals(true)
                            .jetbrainsContractAnnotations(true)
                            .build())
                    .generatorTypes(List.of(
                            GeneratorType.UNDERTOW,
                            GeneratorType.OBJECT,
                            GeneratorType.ERROR,
                            GeneratorType.CHECKED_ERROR))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("async-request")
                    .docs("Generate undertow and jersey objects to test processing async requests.")
                    .files(Path.of("async-request-processing-test.yml"))
                    .options(Options.builder()
                            .undertowServicePrefix(true)
                            .undertowListenableFutures(true)
                            .build())
                    .generatorTypes(List.of(GeneratorType.UNDERTOW, GeneratorType.JERSEY))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("external-fallback-types")
                    .docs("Test generating objects with the external fallback types feature flag enabled.")
                    .files(Path.of("external-types.yml"))
                    .options(Options.builder()
                            .useImmutableBytes(true)
                            .strictObjects(true)
                            .nonNullCollections(true)
                            .excludeEmptyOptionals(true)
                            .unionsWithUnknownValues(true)
                            .jetbrainsContractAnnotations(true)
                            .externalFallbackTypes(true)
                            .build())
                    .generatorTypes(List.of(GeneratorType.UNDERTOW, GeneratorType.DIALOGUE, GeneratorType.OBJECT))
                    .build())
            .add(ParameterizedTestCase.builder()
                    .name("dialogue-endpoint-result-types")
                    .docs("Test generating dialogue interfaces with methods which return endpoint results")
                    .files(List.of(
                            Path.of("src/test/resources/example-endpoint-errors.yml"),
                            Path.of("src/test/resources/errors-for-endpoints.yml")))
                    .options(Options.builder()
                            .generateDialogueEndpointErrorResultTypes(true)
                            .build())
                    .generatorTypes(List.of(
                            GeneratorType.OBJECT,
                            GeneratorType.ERROR,
                            GeneratorType.CHECKED_ERROR,
                            GeneratorType.DIALOGUE,
                            GeneratorType.UNDERTOW))
                    .build())
            .build();

    public static List<ParameterizedTestCase> get() {
        return CASES;
    }

    private TestCases() {}
}
